# Loading important libraries..

In [3]:
#importing important libraries..
!pip install catboost
!pip install imblearn

import warnings, time
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import gc, os
from sklearn.model_selection import StratifiedKFold, cross_validate, GridSearchCV, train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.feature_selection import mutual_info_classif

from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.over_sampling import SMOTE

import xgboost as xgb
import lightgbm as lgb
from catboost import CatBoostClassifier

from sklearn.ensemble import HistGradientBoostingClassifier
from imblearn.ensemble import BalancedRandomForestClassifier
from imblearn.ensemble import EasyEnsembleClassifier


# Display Options
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

# Plot Style
plt.style.use("ggplot")

sns.set_style("whitegrid")
plt.rcParams.update({"figure.dpi": 120, "savefig.dpi": 300, "font.size": 11})
SEED = 42
np.random.seed(SEED)
print("Environment ready")

Collecting catboost
  Downloading catboost-1.2.10-cp313-cp313-manylinux2014_x86_64.whl.metadata (1.4 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.13/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.13/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.13/dist-packages (from catboost) (2.1.3)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.13/dist-packages (from catboost) (2.2.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.13/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.13/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.4)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (1.4.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (4.66.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (1.5.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (3.3.3)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.13/dist-packages (from plotly->catboost) (9.1.4)
Downloading catboost-1.2.10-cp313-cp313-manylinux2014_x86_64.whl (97.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 7.5 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.10
Collecting imblearn
  Downloading imblearn-0.0-py2.py3-none-any.whl.metadata (355 bytes)
Requirement already satisfied: imbalanced-learn in /usr/local/lib/python3.13/dist-packages (from imblearn) (0.14.2)
Requirement already satisfied: numpy<3,>=1.25.2 in /usr/local/lib/python3.13/dist-packages (from imbalanced-learn->imblearn) (2.1.3)
Requirement already satisfied: scipy<2,>=1.11.4 in /usr/local/lib/python3.13/dist-packages (from imbalanced-learn->imblearn) (1.16.3)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in /usr/local/lib/python3.13/dist-packages (from imbalanced-learn->imblearn) (1.6.1)
Requirement already satisfied: sklearn-compat<0.2,>=0.1.6 in /usr/local/lib/python3.13/dist-packages (from imbalanced-learn->imblearn) (0.1.6)
Requirement already satisfied: joblib<2,>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from imbalanced-learn->imblearn) (1.6.0)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from imbalanced-learn->imblearn) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib<2,>=1.2.0->imbalanced-learn->imblearn) (3.1.2)
Downloading imblearn-0.0-py2.py3-none-any.whl (1.9 kB)
Installing collected packages: imblearn
Successfully installed imblearn-0.0
Environment ready

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

#Loading the dataset..

In [5]:
df = pd.read_csv("/content/drive/MyDrive/merged_dataset.csv")
print(df.shape)
print(df.head(5).T)

(447915, 77)
                                        0             1             2  \
Flow Duration               214392.000000  2.376792e+06  1.313500e+05
Total Fwd Packet                 9.000000  9.000000e+00  1.000000e+01
Total Bwd packets               21.000000  3.000000e+00  3.000000e+00
Total Length of Fwd Packet     388.000000  7.520000e+02  7.564000e+03
Total Length of Bwd Packet   24564.000000  0.000000e+00  0.000000e+00
Fwd Packet Length Max          194.000000  1.880000e+02  1.460000e+03
Fwd Packet Length Min            0.000000  0.000000e+00  0.000000e+00
Fwd Packet Length Mean          43.111111  8.355556e+01  7.564000e+02
Fwd Packet Length Std           85.545959  9.908470e+01  6.904973e+02
Bwd Packet Length Max         1460.000000  0.000000e+00  0.000000e+00
Bwd Packet Length Min            0.000000  0.000000e+00  0.000000e+00
Bwd Packet Length Mean        1169.714286  0.000000e+00  0.000000e+00
Bwd Packet Length Std          552.156965  0.000000e+00  0.000000e+00
Flow Bytes/s                116384.939737  3.163929e+02  5.758660e+04
Flow Packets/s                 139.930594  5.048822e+00  9.897221e+01
Flow IAT Mean                 7392.827586  2.160720e+05  1.094583e+04
Flow IAT Std                 17881.622845  6.381799e+05  2.106625e+04
Flow IAT Max                 61855.000000  2.138664e+06  6.294200e+04
Flow IAT Min                     2.000000  1.100000e+01  2.000000e+00
Fwd IAT Total               213501.000000  2.323484e+06  1.190390e+05
Fwd IAT Mean                 26687.625000  2.904355e+05  1.322656e+04
Fwd IAT Std                  35191.916072  7.474109e+05  2.598349e+04
Fwd IAT Max                  87999.000000  2.138664e+06  6.294200e+04
Fwd IAT Min                     10.000000  1.100000e+01  2.000000e+00
Bwd IAT Total               207850.000000  2.357699e+06  1.225950e+05
Bwd IAT Mean                 10392.500000  1.178850e+06  6.129750e+04
Bwd IAT Std                  38260.287131  1.667118e+06  8.667503e+04
Bwd IAT Max                 168673.000000  2.357680e+06  1.225860e+05
Bwd IAT Min                      2.000000  1.900000e+01  9.000000e+00
Fwd PSH Flags                    0.000000  0.000000e+00  0.000000e+00
Bwd PSH Flags                    0.000000  0.000000e+00  0.000000e+00
Fwd URG Flags                    0.000000  0.000000e+00  0.000000e+00
Bwd URG Flags                    0.000000  0.000000e+00  0.000000e+00
Fwd Header Length              212.000000  2.120000e+02  2.320000e+02
Bwd Header Length              436.000000  7.600000e+01  7.600000e+01
Fwd Packets/s                   41.979178  3.786617e+00  7.613247e+01
Bwd Packets/s                   97.951416  1.262206e+00  2.283974e+01
Packet Length Min                0.000000  0.000000e+00  0.000000e+00
Packet Length Max             1460.000000  1.880000e+02  1.460000e+03
Packet Length Mean             804.903226  5.784615e+01  5.402857e+02
Packet Length Std              702.892469  9.031228e+01  6.751505e+02
Packet Length Variance      494057.823656  8.156308e+03  4.558282e+05
FIN Flag Count                   2.000000  2.000000e+00  1.000000e+00
SYN Flag Count                   4.000000  4.000000e+00  4.000000e+00
RST Flag Count                   0.000000  0.000000e+00  0.000000e+00
PSH Flag Count                   2.000000  0.000000e+00  0.000000e+00
ACK Flag Count                  28.000000  1.000000e+01  1.100000e+01
URG Flag Count                   0.000000  0.000000e+00  0.000000e+00
CWR Flag Count                   0.000000  0.000000e+00  0.000000e+00
ECE Flag Count                   0.000000  0.000000e+00  0.000000e+00
Down/Up Ratio                    2.000000  0.000000e+00  0.000000e+00
Average Packet Size            831.733333  6.266667e+01  5.818462e+02
Fwd Segment Size Avg            43.111111  8.355556e+01  7.564000e+02
Bwd Segment Size Avg          1169.714286  0.000000e+00  0.000000e+00
Fwd Bytes/Bulk Avg               0.000000  0.000000e+00  0.000000e+00
Fwd Packet/Bulk Avg              0.000000  0.000000e+00  0.000000e+00
Fwd Bulk Rate Avg                0.000000  0.000000e+00  0.000000e+00
Bwd Bytes/Bulk Avg           24952.000000  0.000000e+00  7.564000e+03
Bwd Packet/Bulk Avg             20.000000  0.000000e+00  6.000000e+00
Bwd Bulk Rate Avg           402393.000000  0.000000e+00  6.367003e+06
Subflow Fwd Packets              0.000000  9.000000e+00  0.000000e+00
Subflow Fwd Bytes                0.000000  7.520000e+02  0.000000e+00
Subflow Bwd Packets              0.000000  3.000000e+00  0.000000e+00
Subflow Bwd Bytes                0.000000  0.000000e+00  0.000000e+00
FWD Init Win Bytes           16383.000000  1.638300e+04  1.638300e+04
Bwd Init Win Bytes           16383.000000  1.638300e+04  1.638300e+04
Fwd Act Data Pkts                2.000000  4.000000e+00  6.000000e+00
Fwd Seg Size Min                20.000000  2.000000e+01  2.000000e+01
Active Mean                      0.000000  0.000000e+00  0.000000e+00
Active Std                       0.000000  0.000000e+00  0.000000e+00
Active Max                       0.000000  0.000000e+00  0.000000e+00
Active Min                       0.000000  0.000000e+00  0.000000e+00
Idle Mean                        0.000000  0.000000e+00  0.000000e+00
Idle Std                         0.000000  0.000000e+00  0.000000e+00
Idle Max                         0.000000  0.000000e+00  0.000000e+00
Idle Min                         0.000000  0.000000e+00  0.000000e+00
Label                            4.000000  7.000000e+00  4.000000e+00

                                        3              4
Flow Duration               164796.000000  163418.000000
Total Fwd Packet                 6.000000       6.000000
Total Bwd packets                3.000000       3.000000
Total Length of Fwd Packet     770.000000     400.000000
Total Length of Bwd Packet       0.000000       0.000000
Fwd Packet Length Max          385.000000     200.000000
Fwd Packet Length Min            0.000000       0.000000
Fwd Packet Length Mean         128.333333      66.666667
Fwd Packet Length Std          198.813145     103.279556
Bwd Packet Length Max            0.000000       0.000000
Bwd Packet Length Min            0.000000       0.000000
Bwd Packet Length Mean           0.000000       0.000000
Bwd Packet Length Std            0.000000       0.000000
Flow Bytes/s                  4672.443506    2447.710778
Flow Packets/s                  54.612976      55.073493
Flow IAT Mean                20599.500000   20427.250000
Flow IAT Std                 26851.824918   27063.749406
Flow IAT Max                 59363.000000   62193.000000
Flow IAT Min                    11.000000      11.000000
Fwd IAT Total               111397.000000  112374.000000
Fwd IAT Mean                 22279.400000   22474.800000
Fwd IAT Std                  30599.330537   31050.388568
Fwd IAT Max                  59363.000000   62193.000000
Fwd IAT Min                     11.000000      11.000000
Bwd IAT Total               157703.000000  157512.000000
Bwd IAT Mean                 78851.500000   78756.000000
Bwd IAT Std                 111495.890151  111359.418542
Bwd IAT Max                 157691.000000  157499.000000
Bwd IAT Min                     12.000000      13.000000
Fwd PSH Flags                    0.000000       0.000000
Bwd PSH Flags                    0.000000       0.000000
Fwd URG Flags                    0.000000       0.000000
Bwd URG Flags                    0.000000       0.000000
Fwd Header Length              152.000000     152.000000
Bwd Header Length               76.000000      76.000000
Fwd Packets/s                   36.408651      36.715662
Bwd Packets/s                   18.204325      18.357831
Packet Length Min                0.000000       0.000000
Packet Length Max              385.000000     200.000000
Packet Length Mean              77.000000      40.000000
Packet Length Std              162.330253      84.327404
Packet Length Variance       26351.111111    7111.111111
FIN Flag Count                   1.000000       1.000000
SYN Flag Count                   4.000000       4.000000
RST Flag Count                   0.000000       0.000000
PSH Flag Count                   0.000000       0.000000
ACK Flag Count                   7.000000       7.000000
URG Flag Count                   0.000000       0.000000
CWR Flag Count                   0.000000       0.000000
ECE Flag Count                   0.000000       0.000000
Down/Up Ratio                    0.000000       0.000000
Average Packet Size             85.555556      44.444444
Fwd Segment Size Avg           128.333333      66.666667
Bwd Segment Size Avg             0.000000       0.000000
Fwd Bytes/Bulk Avg               0.000000       0.000000
Fwd Packet/Bulk Avg              0.000000       0.000000
Fwd Bulk Rate Avg                0.000000       0.000000
Bwd Bytes/Bulk Avg               0.000000       0.000000
Bwd Packet/Bulk Avg              0.000000       0.000000
Bwd Bulk Rate Avg                0.000000       0.000000
Subflow Fwd Packets              0.000000       0.000000
Subflow Fwd Bytes                0.000000       0.000000
Subflow Bwd Packets              0.000000       0.000000
Subflow Bwd Bytes                0.000000       0.000000
FWD Init Win Bytes           16383.000000   16383.000000
Bwd Init Win Bytes           16383.000000   16383.000000
Fwd Act Data Pkts                2.000000       2.000000
Fwd Seg Size Min                20.000000      20.000000
Active Mean                      0.000000       0.000000
Active Std                       0.000000       0.000000
Active Max                       0.000000       0.000000
Active Min                       0.000000       0.000000
Idle Mean                        0.000000       0.000000
Idle Std                         0.000000       0.000000
Idle Max                         0.000000       0.000000
Idle Min                         0.000000       0.000000
Label                            3.000000       6.000000

In [6]:
import shutil
import os

source_path = "/content/drive/MyDrive/merged_dataset.csv"
local_path = "/content/merged_dataset.csv"

# Safely copy the file from Drive to local workspace
if os.path.exists(source_path):
    print("Copying file to local runtime storage for stability...")
    shutil.copyfile(source_path, local_path)
    print("Copy complete.")
else:
    print("Source path not found. Please ensure the file name and path are correct.")

# Read the stable local copy
df = pd.read_csv(local_path)
print("Stable local dataset shape:", df.shape)

Copying file to local runtime storage for stability...
Copy complete.
Stable local dataset shape: (447915, 77)

In [7]:
print(df.shape)
print("------------------------------------------------------------------------")
print(df.info())
print("------------------------------------------------------------------------")
print(df.describe().T)
print("------------------------------------------------------------------------")
print(np.isinf(df.select_dtypes(include=np.number)).sum().sum())
print("------------------------------------------------------------------------")
print(df.isnull().sum().sum())
print("------------------------------------------------------------------------")
print(f"The number of duplicated values in the dataset is : {df.duplicated().sum()}")
print("------------------------------------------------------------------------")
df.columns = df.columns.str.strip()
print(df.columns.to_list())

(447915, 77)
------------------------------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 447915 entries, 0 to 447914
Data columns (total 77 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Flow Duration               447915 non-null  int64
 1   Total Fwd Packet            447915 non-null  int64
 2   Total Bwd packets           447915 non-null  int64
 3   Total Length of Fwd Packet  447915 non-null  float64
 4   Total Length of Bwd Packet  447915 non-null  float64
 5   Fwd Packet Length Max       447915 non-null  float64
 6   Fwd Packet Length Min       447915 non-null  float64
 7   Fwd Packet Length Mean      447915 non-null  float64
 8   Fwd Packet Length Std       447915 non-null  float64
 9   Bwd Packet Length Max       447915 non-null  float64
 10  Bwd Packet Length Min       447915 non-null  float64
 11  Bwd Packet Length Mean      447915 non-null  float64
 12  Bwd Packet Length Std       447915 non-null  float64
 13  Flow Bytes/s                447915 non-null  float64
 14  Flow Packets/s              447915 non-null  float64
 15  Flow IAT Mean               447915 non-null  float64
 16  Flow IAT Std                447915 non-null  float64
 17  Flow IAT Max                447915 non-null  float64
 18  Flow IAT Min                447915 non-null  float64
 19  Fwd IAT Total               447915 non-null  float64
 20  Fwd IAT Mean                447915 non-null  float64
 21  Fwd IAT Std                 447915 non-null  float64
 22  Fwd IAT Max                 447915 non-null  float64
 23  Fwd IAT Min                 447915 non-null  float64
 24  Bwd IAT Total               447915 non-null  float64
 25  Bwd IAT Mean                447915 non-null  float64
 26  Bwd IAT Std                 447915 non-null  float64
 27  Bwd IAT Max                 447915 non-null  float64
 28  Bwd IAT Min                 447915 non-null  float64
 29  Fwd PSH Flags               447915 non-null  int64
 30  Bwd PSH Flags               447915 non-null  int64
 31  Fwd URG Flags               447915 non-null  int64
 32  Bwd URG Flags               447915 non-null  int64
 33  Fwd Header Length           447915 non-null  int64
 34  Bwd Header Length           447915 non-null  int64
 35  Fwd Packets/s               447915 non-null  float64
 36  Bwd Packets/s               447915 non-null  float64
 37  Packet Length Min           447915 non-null  float64
 38  Packet Length Max           447915 non-null  float64
 39  Packet Length Mean          447915 non-null  float64
 40  Packet Length Std           447915 non-null  float64
 41  Packet Length Variance      447915 non-null  float64
 42  FIN Flag Count              447915 non-null  int64
 43  SYN Flag Count              447915 non-null  int64
 44  RST Flag Count              447915 non-null  int64
 45  PSH Flag Count              447915 non-null  int64
 46  ACK Flag Count              447915 non-null  int64
 47  URG Flag Count              447915 non-null  int64
 48  CWR Flag Count              447915 non-null  int64
 49  ECE Flag Count              447915 non-null  int64
 50  Down/Up Ratio               447915 non-null  float64
 51  Average Packet Size         447915 non-null  float64
 52  Fwd Segment Size Avg        447915 non-null  float64
 53  Bwd Segment Size Avg        447915 non-null  float64
 54  Fwd Bytes/Bulk Avg          447915 non-null  int64
 55  Fwd Packet/Bulk Avg         447915 non-null  int64
 56  Fwd Bulk Rate Avg           447915 non-null  int64
 57  Bwd Bytes/Bulk Avg          447915 non-null  int64
 58  Bwd Packet/Bulk Avg         447915 non-null  int64
 59  Bwd Bulk Rate Avg           447915 non-null  int64
 60  Subflow Fwd Packets         447915 non-null  int64
 61  Subflow Fwd Bytes           447915 non-null  int64
 62  Subflow Bwd Packets         447915 non-null  int64
 63  Subflow Bwd Bytes           447915 non-null  int64
 64  FWD Init Win Bytes          447915 non-null  int64
 65  Bwd Init Win Bytes          447915 non-null  int64
 66  Fwd Act Data Pkts           447915 non-null  int64
 67  Fwd Seg Size Min            447915 non-null  int64
 68  Active Mean                 447915 non-null  float64
 69  Active Std                  447915 non-null  float64
 70  Active Max                  447915 non-null  float64
 71  Active Min                  447915 non-null  float64
 72  Idle Mean                   447915 non-null  float64
 73  Idle Std                    447915 non-null  float64
 74  Idle Max                    447915 non-null  float64
 75  Idle Min                    447915 non-null  float64
 76  Label                       447915 non-null  int64
dtypes: float64(45), int64(32)
memory usage: 263.1 MB
None
------------------------------------------------------------------------
                               count          mean           std       min  \
Flow Duration               447915.0  5.983003e+05  4.878777e+06  1.000000
Total Fwd Packet            447915.0  2.259843e+01  1.279869e+02  1.000000
Total Bwd packets           447915.0  2.723850e+01  1.166388e+02  0.000000
Total Length of Fwd Packet  447915.0  4.778406e+03  1.518561e+05  0.000000
Total Length of Bwd Packet  447915.0  2.170251e+04  1.477431e+05  0.000000
Fwd Packet Length Max       447915.0  1.742432e+02  3.521714e+02  0.000000
Fwd Packet Length Min       447915.0  1.491836e+01  7.157057e+01  0.000000
Fwd Packet Length Mean      447915.0  7.126432e+01  1.845653e+02  0.000000
Fwd Packet Length Std       447915.0  6.400087e+01  1.563874e+02  0.000000
Bwd Packet Length Max       447915.0  3.650100e+02  5.558085e+02  0.000000
Bwd Packet Length Min       447915.0  6.676934e+00  2.021041e+01  0.000000
Bwd Packet Length Mean      447915.0  1.728889e+02  3.090726e+02  0.000000
Bwd Packet Length Std       447915.0  1.510945e+02  2.468496e+02  0.000000
Flow Bytes/s                447915.0  2.496622e+06  2.532600e+07  0.000000
Flow Packets/s              447915.0  1.641171e+04  9.426925e+04  0.034598
Flow IAT Mean               447915.0  2.406832e+04  4.055051e+05  1.000000
Flow IAT Std                447915.0  5.381697e+04  8.028215e+05  0.000000
Flow IAT Max                447915.0  2.250955e+05  2.283272e+06  1.000000
Flow IAT Min                447915.0  1.304782e+02  3.465052e+04  0.000000
Fwd IAT Total               447915.0  5.738608e+05  4.870867e+06  0.000000
Fwd IAT Mean                447915.0  3.418049e+04  4.422963e+05  0.000000
Fwd IAT Std                 447915.0  6.946663e+04  8.982025e+05  0.000000
Fwd IAT Max                 447915.0  2.277712e+05  2.280900e+06  0.000000
Fwd IAT Min                 447915.0  1.391330e+02  3.516312e+04  0.000000
Bwd IAT Total               447915.0  4.367117e+05  2.869326e+06  0.000000
Bwd IAT Mean                447915.0  3.432153e+04  3.709524e+05  0.000000
Bwd IAT Std                 447915.0  6.619141e+04  7.979521e+05  0.000000
Bwd IAT Max                 447915.0  2.102458e+05  1.947234e+06  0.000000
Bwd IAT Min                 447915.0  6.394948e+00  1.594452e+03  0.000000
Fwd PSH Flags               447915.0  6.787002e-04  2.604306e-02  0.000000
Bwd PSH Flags               447915.0  0.000000e+00  0.000000e+00  0.000000
Fwd URG Flags               447915.0  0.000000e+00  0.000000e+00  0.000000
Bwd URG Flags               447915.0  0.000000e+00  0.000000e+00  0.000000
Fwd Header Length           447915.0  6.644922e+02  2.835744e+03  8.000000
Bwd Header Length           447915.0  8.253895e+02  3.210005e+03  0.000000
Fwd Packets/s               447915.0  1.367719e+04  9.450798e+04  0.034598
Bwd Packets/s               447915.0  2.734518e+03  3.241360e+03  0.000000
Packet Length Min           447915.0  1.215863e+01  6.823578e+01  0.000000
Packet Length Max           447915.0  4.706285e+02  5.972735e+02  0.000000
Packet Length Mean          447915.0  1.391902e+02  2.150687e+02  0.000000
Packet Length Std           447915.0  1.789063e+02  2.504678e+02  0.000000
Packet Length Variance      447915.0  9.474147e+04  1.566062e+05  0.000000
FIN Flag Count              447915.0  9.375060e-01  5.065833e-01  0.000000
SYN Flag Count              447915.0  1.802815e+00  1.990091e+00  0.000000
RST Flag Count              447915.0  1.093958e-04  1.045868e-02  0.000000
PSH Flag Count              447915.0  1.750762e+01  5.173739e+01  0.000000
ACK Flag Count              447915.0  4.807745e+01  2.100060e+02  0.000000
URG Flag Count              447915.0  0.000000e+00  0.000000e+00  0.000000
CWR Flag Count              447915.0  0.000000e+00  0.000000e+00  0.000000
ECE Flag Count              447915.0  0.000000e+00  0.000000e+00  0.000000
Down/Up Ratio               447915.0  1.095989e+00  1.774969e+00  0.000000
Average Packet Size         447915.0  1.471572e+02  2.284246e+02  0.000000
Fwd Segment Size Avg        447915.0  7.126432e+01  1.845653e+02  0.000000
Bwd Segment Size Avg        447915.0  1.728889e+02  3.090726e+02  0.000000
Fwd Bytes/Bulk Avg          447915.0  0.000000e+00  0.000000e+00  0.000000
Fwd Packet/Bulk Avg         447915.0  0.000000e+00  0.000000e+00  0.000000
Fwd Bulk Rate Avg           447915.0  0.000000e+00  0.000000e+00  0.000000
Bwd Bytes/Bulk Avg          447915.0  2.208449e+04  1.928710e+05  0.000000
Bwd Packet/Bulk Avg         447915.0  2.541025e+01  1.496777e+02  0.000000
Bwd Bulk Rate Avg           447915.0  5.867066e+05  1.014900e+07  0.000000
Subflow Fwd Packets         447915.0  3.204813e+00  7.347096e+01  0.000000
Subflow Fwd Bytes           447915.0  9.636264e+02  8.837936e+04  0.000000
Subflow Bwd Packets         447915.0  4.990581e+00  7.468962e+01  0.000000
Subflow Bwd Bytes           447915.0  5.809794e+03  9.411375e+04  0.000000
FWD Init Win Bytes          447915.0  1.338908e+04  1.389461e+04  0.000000
Bwd Init Win Bytes          447915.0  1.389376e+04  1.088819e+04  0.000000
Fwd Act Data Pkts           447915.0  8.628521e+00  1.186633e+02  0.000000
Fwd Seg Size Min            447915.0  2.592665e+01  9.017636e+00  8.000000
Active Mean                 447915.0  1.868487e+04  7.487275e+05  0.000000
Active Std                  447915.0  9.409518e+03  5.231382e+05  0.000000
Active Max                  447915.0  3.126578e+04  1.174788e+06  0.000000
Active Min                  447915.0  1.252120e+04  6.397847e+05  0.000000
Idle Mean                   447915.0  9.859284e+04  2.222806e+06  0.000000
Idle Std                    447915.0  3.341817e+03  2.201782e+05  0.000000
Idle Max                    447915.0  1.026228e+05  2.260988e+06  0.000000
Idle Min                    447915.0  9.578854e+04  2.207332e+06  0.000000
Label                       447915.0  1.005829e+00  2.095053e+00  0.000000

                                    25%           50%            75%  \
Flow Duration                349.000000   5788.000000  179240.500000
Total Fwd Packet               1.000000      3.000000      17.000000
Total Bwd packets              2.000000      2.000000      15.000000
Total Length of Fwd Packet     0.000000     90.000000     486.000000
Total Length of Bwd Packet     0.000000    106.000000    1512.000000
Fwd Packet Length Max          0.000000     45.000000     163.000000
Fwd Packet Length Min          0.000000      0.000000       0.000000
Fwd Packet Length Mean         0.000000      9.346154      50.000000
Fwd Packet Length Std          0.000000      0.000000      29.277002
Bwd Packet Length Max          0.000000     48.000000     731.000000
Bwd Packet Length Min          0.000000      0.000000       0.000000
Bwd Packet Length Mean         0.000000     18.156863     100.800000
Bwd Packet Length Std          0.000000      0.000000     202.416167
Flow Bytes/s                   0.000000   5022.761402  202676.864245
Flow Packets/s               107.927386   3802.281369    8620.689655
Flow IAT Mean                169.500000    338.000000   10237.000000
Flow IAT Std                 239.002092    586.011376   21904.707676
Flow IAT Max                 346.000000   1692.000000   69726.000000
Flow IAT Min                   1.000000      2.000000       4.000000
Fwd IAT Total                  0.000000   3918.000000  125031.000000
Fwd IAT Mean                   0.000000    314.743590   14086.507353
Fwd IAT Std                    0.000000    487.272787   26486.098703
Fwd IAT Max                    0.000000   1410.000000   60077.500000
Fwd IAT Min                    0.000000      1.000000       3.000000
Bwd IAT Total                  3.000000     10.000000  155829.000000
Bwd IAT Mean                   3.000000     10.000000    6392.219508
Bwd IAT Std                    0.000000      0.000000   15136.732286
Bwd IAT Max                    3.000000     10.000000   57312.000000
Bwd IAT Min                    1.000000      2.000000       4.000000
Fwd PSH Flags                  0.000000      0.000000       0.000000
Bwd PSH Flags                  0.000000      0.000000       0.000000
Fwd URG Flags                  0.000000      0.000000       0.000000
Bwd URG Flags                  0.000000      0.000000       0.000000
Fwd Header Length             32.000000     60.000000     492.000000
Bwd Header Length             64.000000     64.000000     488.000000
Fwd Packets/s                 56.844187   1891.021151    2949.852507
Bwd Packets/s                 33.875052   1836.547291    5602.240896
Packet Length Min              0.000000      0.000000       0.000000
Packet Length Max              0.000000     61.000000    1300.000000
Packet Length Mean             0.000000     44.400000     217.200000
Packet Length Std              0.000000      8.763561     427.643812
Packet Length Variance         0.000000     76.800000  182879.229837
FIN Flag Count                 1.000000      1.000000       1.000000
SYN Flag Count                 0.000000      0.000000       4.000000
RST Flag Count                 0.000000      0.000000       0.000000
PSH Flag Count                 0.000000      0.000000      12.000000
ACK Flag Count                 3.000000      5.000000      30.000000
URG Flag Count                 0.000000      0.000000       0.000000
CWR Flag Count                 0.000000      0.000000       0.000000
ECE Flag Count                 0.000000      0.000000       0.000000
Down/Up Ratio                  0.000000      1.000000       2.000000
Average Packet Size            0.000000     54.250000     230.222222
Fwd Segment Size Avg           0.000000      9.346154      50.000000
Bwd Segment Size Avg           0.000000     18.156863     100.800000
Fwd Bytes/Bulk Avg             0.000000      0.000000       0.000000
Fwd Packet/Bulk Avg            0.000000      0.000000       0.000000
Fwd Bulk Rate Avg              0.000000      0.000000       0.000000
Bwd Bytes/Bulk Avg             0.000000    180.000000    7682.000000
Bwd Packet/Bulk Avg            0.000000      4.000000      20.000000
Bwd Bulk Rate Avg              0.000000   1359.000000  199061.000000
Subflow Fwd Packets            0.000000      0.000000       0.000000
Subflow Fwd Bytes              0.000000      0.000000       0.000000
Subflow Bwd Packets            0.000000      0.000000       0.000000
Subflow Bwd Bytes              0.000000      0.000000       0.000000
FWD Init Win Bytes          5792.000000   8688.000000   16383.000000
Bwd Init Win Bytes          8688.000000  14480.000000   16383.000000
Fwd Act Data Pkts              0.000000      1.000000      10.000000
Fwd Seg Size Min              20.000000     32.000000      32.000000
Active Mean                    0.000000      0.000000       0.000000
Active Std                     0.000000      0.000000       0.000000
Active Max                     0.000000      0.000000       0.000000
Active Min                     0.000000      0.000000       0.000000
Idle Mean                      0.000000      0.000000       0.000000
Idle Std                       0.000000      0.000000       0.000000
Idle Max                       0.000000      0.000000       0.000000
Idle Min                       0.000000      0.000000       0.000000
Label                          0.000000      0.000000       0.000000

                                     max
Flow Duration               1.199975e+08
Total Fwd Packet            2.003800e+04
Total Bwd packets           1.102100e+04
Total Length of Fwd Packet  2.605270e+07
Total Length of Bwd Packet  1.421599e+07
Fwd Packet Length Max       1.476000e+03
Fwd Packet Length Min       1.472000e+03
Fwd Packet Length Mean      1.474000e+03
Fwd Packet Length Std       8.485281e+02
Bwd Packet Length Max       1.460000e+03
Bwd Packet Length Min       1.300000e+03
Bwd Packet Length Mean      1.424937e+03
Bwd Packet Length Std       8.360032e+02
Flow Bytes/s                1.469000e+09
Flow Packets/s              2.000000e+06
Flow IAT Mean               4.218575e+07
Flow IAT Std                6.674908e+07
Flow IAT Max                1.191926e+08
Flow IAT Min                1.299983e+07
Fwd IAT Total               1.199974e+08
Fwd IAT Mean                4.218575e+07
Fwd IAT Std                 6.674908e+07
Fwd IAT Max                 1.192316e+08
Fwd IAT Min                 1.299983e+07
Bwd IAT Total               1.199672e+08
Bwd IAT Mean                3.257174e+07
Bwd IAT Std                 5.956505e+07
Bwd IAT Max                 1.192933e+08
Bwd IAT Min                 1.002456e+06
Fwd PSH Flags               1.000000e+00
Bwd PSH Flags               0.000000e+00
Fwd URG Flags               0.000000e+00
Bwd URG Flags               0.000000e+00
Fwd Header Length           4.007920e+05
Bwd Header Length           2.204360e+05
Fwd Packets/s               2.000000e+06
Bwd Packets/s               3.333333e+04
Packet Length Min           1.472000e+03
Packet Length Max           1.476000e+03
Packet Length Mean          1.474667e+03
Packet Length Std           7.931023e+02
Packet Length Variance      6.290112e+05
FIN Flag Count              3.000000e+00
SYN Flag Count              1.200000e+01
RST Flag Count              1.000000e+00
PSH Flag Count              6.960000e+02
ACK Flag Count              2.303000e+04
URG Flag Count              0.000000e+00
CWR Flag Count              0.000000e+00
ECE Flag Count              0.000000e+00
Down/Up Ratio               4.000000e+02
Average Packet Size         2.212000e+03
Fwd Segment Size Avg        1.474000e+03
Bwd Segment Size Avg        1.424937e+03
Fwd Bytes/Bulk Avg          0.000000e+00
Fwd Packet/Bulk Avg         0.000000e+00
Fwd Bulk Rate Avg           0.000000e+00
Bwd Bytes/Bulk Avg          2.605314e+07
Bwd Packet/Bulk Avg         2.004200e+04
Bwd Bulk Rate Avg           8.476667e+08
Subflow Fwd Packets         1.113100e+04
Subflow Fwd Bytes           1.421575e+07
Subflow Bwd Packets         1.102100e+04
Subflow Bwd Bytes           1.421599e+07
FWD Init Win Bytes          6.541800e+04
Bwd Init Win Bytes          6.551800e+04
Fwd Act Data Pkts           2.003200e+04
Fwd Seg Size Min            4.000000e+01
Active Mean                 1.104063e+08
Active Std                  7.417760e+07
Active Max                  1.104063e+08
Active Min                  1.104063e+08
Idle Mean                   1.191926e+08
Idle Std                    7.214360e+07
Idle Max                    1.191926e+08
Idle Min                    1.191926e+08
Label                       9.000000e+00
------------------------------------------------------------------------
0
------------------------------------------------------------------------
0
------------------------------------------------------------------------
The number of duplicated values in the dataset is : 141742
------------------------------------------------------------------------

Duplicate handling...

In [8]:
# ==========================================
# DUPLICATE HANDLING
# ==========================================

print("Before duplicate removal:")
print("Rows:", len(df))
l_df = len(df)

df = (
    df
    .drop_duplicates()
    .reset_index(drop=True)
)

print("\nAfter duplicate removal:")
print("Rows:", len(df))

print("\nRows removed:", l_df - len(df))

print(
    "Percentage removed:",
    round((l_df - len(df)) / l_df * 100, 2),
    "%"
)

Before duplicate removal:
Rows: 447915

After duplicate removal:
Rows: 306173

Rows removed: 141742
Percentage removed: 31.64 %

In [9]:
# ==============================
# STEP 1: DATA PREPARATION
# ==============================

# Separate features and target
X = df.drop(columns=["Label"]).copy()
y = df["Label"].copy()

print("Feature shape:", X.shape)
print("Target shape:", y.shape)

print("\nClass distribution:")
print(y.value_counts().sort_index())

print("\nMissing values:", X.isna().sum().sum())
print("Infinite values:", np.isinf(X.select_dtypes(include=np.number)).sum().sum())

Feature shape: (306173, 76)
Target shape: (306173,)

Class distribution:
Label
0    225003
1       385
2       452
3      4412
4     30910
5     26395
6      4496
7     12031
8      1848
9       241
Name: count, dtype: int64

Missing values: 0
Infinite values: 0

In [10]:
# ==========================================
# STEP 2: LEAKAGE-SAFE TRAIN / TEST SPLIT
# ==========================================

from sklearn.model_selection import StratifiedGroupKFold

# Create a group ID for identical feature vectors
groups = pd.util.hash_pandas_object(
    X,
    index=False
)

print("Total samples:", len(X))
print("Unique feature groups:", groups.nunique())

# 5-fold stratified group split
sgkf = StratifiedGroupKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

train_idx, test_idx = next(
    sgkf.split(X, y, groups=groups)
)

# Create final train and test sets
X_train = X.iloc[train_idx].copy()
X_test = X.iloc[test_idx].copy()

y_train = y.iloc[train_idx].copy()
y_test = y.iloc[test_idx].copy()

groups_train = groups.iloc[train_idx]
groups_test = groups.iloc[test_idx]

# ------------------------------------------
# Verify split
# ------------------------------------------

print("\nTrain shape:", X_train.shape)
print("Test shape:", X_test.shape)

print("\nTrain class distribution:")
print(y_train.value_counts(normalize=True).sort_index())

print("\nTest class distribution:")
print(y_test.value_counts(normalize=True).sort_index())

# Check for identical feature groups across train/test
overlap = set(groups_train).intersection(set(groups_test))

print("\nFeature-group overlap:", len(overlap))

Total samples: 306173
Unique feature groups: 305602

Train shape: (244946, 76)
Test shape: (61227, 76)

Train class distribution:
Label
0    0.735060
1    0.001229
2    0.001449
3    0.014485
4    0.100892
5    0.085970
6    0.014722
7    0.039364
8    0.006014
9    0.000817
Name: proportion, dtype: float64

Test class distribution:
Label
0    0.734202
1    0.001372
2    0.001584
3    0.014111
4    0.101214
5    0.087167
6    0.014536
7    0.039019
8    0.006125
9    0.000670
Name: proportion, dtype: float64

Feature-group overlap: 0

In [11]:
# ==========================================
# STEP 3: DEVELOPMENT SUBSET
# ==========================================

from sklearn.model_selection import train_test_split

# Create development subset from TRAINING DATA ONLY
X_dev, _, y_dev, _ = train_test_split(
    X_train,
    y_train,
    train_size=120_000,
    stratify=y_train,
    random_state=42
)

print("Development feature shape:", X_dev.shape)
print("Development target shape:", y_dev.shape)

print("\nDevelopment class distribution:")
print(y_dev.value_counts(normalize=True).sort_index())

print("\nFinal test set remains:")
print("X_test:", X_test.shape)
print("y_test:", y_test.shape)

Development feature shape: (120000, 76)
Development target shape: (120000,)

Development class distribution:
Label
0    0.735058
1    0.001225
2    0.001450
3    0.014483
4    0.100892
5    0.085967
6    0.014725
7    0.039367
8    0.006017
9    0.000817
Name: proportion, dtype: float64

Final test set remains:
X_test: (61227, 76)
y_test: (61227,)

In [12]:
# ============================================================
# STEP 4: PREPROCESSING & MODEL PIPELINE ARCHITECTURE
# ============================================================

# ------------------------------------------------------------
# 1. Imports
# ------------------------------------------------------------

from sklearn.pipeline import Pipeline
from imblearn.pipeline import Pipeline as ImbPipeline

from sklearn.compose import ColumnTransformer

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import (
    StandardScaler,
    OneHotEncoder
)

from imblearn.over_sampling import SMOTE


# ------------------------------------------------------------
# 2. Reproducibility
# ------------------------------------------------------------

SEED = 42


# ------------------------------------------------------------
# 3. Identify Feature Types
# ------------------------------------------------------------

num_cols = X_train.select_dtypes(
    include=["number"]
).columns.tolist()

cat_cols = X_train.select_dtypes(
    exclude=["number"]
).columns.tolist()


print("=" * 55)
print("FEATURE TYPE SUMMARY")
print("=" * 55)

print(f"Numerical Features   : {len(num_cols)}")
print(f"Categorical Features : {len(cat_cols)}")


# ------------------------------------------------------------
# 4. Numerical Preprocessing Pipeline
# ------------------------------------------------------------

def create_numeric_pipeline(scale=False):
    """
    Create preprocessing pipeline for numerical features.

    Parameters
    ----------
    scale : bool, default=False
        Whether to apply StandardScaler.

    Returns
    -------
    Pipeline
        Numerical preprocessing pipeline.
    """

    steps = [
        (
            "imputer",
            SimpleImputer(strategy="median")
        )
    ]

    if scale:
        steps.append(
            (
                "scaler",
                StandardScaler()
            )
        )

    return Pipeline(steps)


# ------------------------------------------------------------
# 5. Categorical Preprocessing Pipeline
# ------------------------------------------------------------

def create_categorical_pipeline():
    """
    Create preprocessing pipeline for categorical features.

    Returns
    -------
    Pipeline
        Categorical preprocessing pipeline.
    """

    return Pipeline([
        (
            "imputer",
            SimpleImputer(strategy="most_frequent")
        ),

        (
            "onehot",
            OneHotEncoder(
                handle_unknown="ignore"
            )
        )
    ])


# ------------------------------------------------------------
# 6. Create Column-Wise Preprocessor
# ------------------------------------------------------------

def create_preprocessor(
    num_cols,
    cat_cols,
    scale=False
):
    """
    Create a column-wise preprocessing transformer.

    Numerical features:
        Median imputation
        Optional standardization

    Categorical features:
        Most-frequent imputation
        One-hot encoding

    Parameters
    ----------
    num_cols : list
        Numerical feature names.

    cat_cols : list
        Categorical feature names.

    scale : bool, default=False
        Whether numerical features should be standardized.

    Returns
    -------
    ColumnTransformer
        Combined preprocessing transformer.
    """

    transformers = []

    # Numerical features
    if num_cols:

        transformers.append(
            (
                "num",
                create_numeric_pipeline(
                    scale=scale
                ),
                num_cols
            )
        )

    # Categorical features
    if cat_cols:

        transformers.append(
            (
                "cat",
                create_categorical_pipeline(),
                cat_cols
            )
        )

    return ColumnTransformer(
        transformers=transformers,
        remainder="drop"
    )


# ------------------------------------------------------------
# 7. General Model Pipeline Builder
# ------------------------------------------------------------

def build_pipeline(
    model,
    num_cols,
    cat_cols,
    scale=False,
    sampler=None
):
    """
    Build a complete leakage-safe ML pipeline.

    Pipeline structure:

        Raw Data
            ↓
        Preprocessor
            ↓
        Optional Sampler
            ↓
        Model

    Parameters
    ----------
    model : estimator
        Machine learning model.

    num_cols : list
        Numerical feature names.

    cat_cols : list
        Categorical feature names.

    scale : bool, default=False
        Whether numerical features should be standardized.

    sampler : sampler or None, default=None
        Optional imbalance-handling sampler such as SMOTE.

    Returns
    -------
    ImbPipeline
        Complete preprocessing + sampling + model pipeline.
    """

    preprocessor = create_preprocessor(
        num_cols=num_cols,
        cat_cols=cat_cols,
        scale=scale
    )

    steps = [
        (
            "preprocessor",
            preprocessor
        )
    ]

    # Optional imbalance-handling step
    if sampler is not None:

        steps.append(
            (
                "sampler",
                sampler
            )
        )

    # Final estimator
    steps.append(
        (
            "model",
            model
        )
    )

    return ImbPipeline(steps)


# ------------------------------------------------------------
# 8. Architecture Verification
# ------------------------------------------------------------

print("\n" + "=" * 55)
print("PIPELINE ARCHITECTURE READY")
print("=" * 55)

print("Preprocessing : ColumnTransformer")
print("Numerical     : Median Imputation")
print("Scaling       : Model-dependent")
print("Categorical   : Imputation + One-Hot Encoding")
print("Sampling      : Optional")
print("Model         : Configurable")
print("Leakage Safe  : Yes")

=======================================================
FEATURE TYPE SUMMARY
=======================================================
Numerical Features   : 76
Categorical Features : 0

=======================================================
PIPELINE ARCHITECTURE READY
=======================================================
Preprocessing : ColumnTransformer
Numerical     : Median Imputation
Scaling       : Model-dependent
Categorical   : Imputation + One-Hot Encoding
Sampling      : Optional
Model         : Configurable
Leakage Safe  : Yes

In [13]:
# ============================================================
# STEP 5: MODEL REGISTRY
# ============================================================

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import (
    RandomForestClassifier,
    HistGradientBoostingClassifier
)


# ------------------------------------------------------------
# 1. Model Registry
# ------------------------------------------------------------
 ## Models which doesn't use smote..

MODEL_REGISTRY = {

    # --------------------------------------------------------
    # Logistic Regression
    # --------------------------------------------------------
    "Logistic Regression": {
        "model": LogisticRegression(
            max_iter=1000,
            random_state=SEED
        ),
        "scale": True,
        "sampler": None
    },


    # --------------------------------------------------------
    # Decision Tree
    # --------------------------------------------------------
    "Decision Tree": {
        "model": DecisionTreeClassifier(
            random_state=SEED
        ),
        "scale": False,
        "sampler": None
    },


    # --------------------------------------------------------
    # Random Forest
    # --------------------------------------------------------
    "Random Forest": {
        "model": RandomForestClassifier(
            n_estimators=200,
            random_state=SEED,
            n_jobs=-1
        ),
        "scale": False,
        "sampler": None
    },


    # --------------------------------------------------------
    # Histogram Gradient Boosting
    # --------------------------------------------------------
    "HistGradientBoosting": {
        "model": HistGradientBoostingClassifier(
            random_state=SEED
        ),
        "scale": False,
        "sampler": None
    }
}


# ------------------------------------------------------------
# 2. Build Model Pipelines
# ------------------------------------------------------------

PIPELINES = {}

for model_name, config in MODEL_REGISTRY.items():

    PIPELINES[model_name] = build_pipeline(
        model=config["model"],
        num_cols=num_cols,
        cat_cols=cat_cols,
        scale=config["scale"],
        sampler=config["sampler"]
    )


# ------------------------------------------------------------
# 3. Registry Summary
# ------------------------------------------------------------

print("=" * 60)
print("MODEL REGISTRY")
print("=" * 60)

for model_name, config in MODEL_REGISTRY.items():

    print(
        f"{model_name:<25} | "
        f"Scaling: {str(config['scale']):<5} | "
        f"Sampler: "
        f"{type(config['sampler']).__name__ if config['sampler'] else 'None'}"
    )

print("=" * 60)
print(f"Total models registered: {len(PIPELINES)}")

============================================================
MODEL REGISTRY
============================================================
Logistic Regression       | Scaling: True  | Sampler: None
Decision Tree             | Scaling: False | Sampler: None
Random Forest             | Scaling: False | Sampler: None
HistGradientBoosting      | Scaling: False | Sampler: None
============================================================
Total models registered: 4

In [14]:
# ============================================================
# STEP 6: REUSABLE EVALUATION ENGINE
# ============================================================

import time
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay
)


# ------------------------------------------------------------
# 1. Model Evaluation Function
# ------------------------------------------------------------

def evaluate_model(
    model_name,
    pipeline,
    X_train_data,
    y_train_data,
    X_eval_data,
    y_eval_data,
    show_report=True,
    show_confusion_matrix=True
):
    """
    Train and evaluate a model using a unified evaluation protocol.
    """

    print("\n" + "=" * 70)
    print(f"MODEL: {model_name}")
    print("=" * 70)

    # --------------------------------------------------------
    # Training
    # --------------------------------------------------------

    start_train = time.perf_counter()

    pipeline.fit(
        X_train_data,
        y_train_data
    )

    train_time = time.perf_counter() - start_train


    # --------------------------------------------------------
    # Prediction
    # --------------------------------------------------------

    start_predict = time.perf_counter()

    y_pred = pipeline.predict(
        X_eval_data
    )

    prediction_time = time.perf_counter() - start_predict


    # --------------------------------------------------------
    # Metrics
    # --------------------------------------------------------

    accuracy = accuracy_score(
        y_eval_data,
        y_pred
    )

    macro_precision = precision_score(
        y_eval_data,
        y_pred,
        average="macro",
        zero_division=0
    )

    macro_recall = recall_score(
        y_eval_data,
        y_pred,
        average="macro",
        zero_division=0
    )

    macro_f1 = f1_score(
        y_eval_data,
        y_pred,
        average="macro",
        zero_division=0
    )

    weighted_f1 = f1_score(
        y_eval_data,
        y_pred,
        average="weighted",
        zero_division=0
    )


    # --------------------------------------------------------
    # Summary
    # --------------------------------------------------------

    print(f"\nTraining Time   : {train_time:.2f} seconds")
    print(f"Prediction Time : {prediction_time:.2f} seconds")

    print(f"\nAccuracy        : {accuracy:.4f}")
    print(f"Macro Precision : {macro_precision:.4f}")
    print(f"Macro Recall    : {macro_recall:.4f}")
    print(f"Macro F1        : {macro_f1:.4f}")
    print(f"Weighted F1     : {weighted_f1:.4f}")


    # --------------------------------------------------------
    # Classification Report
    # --------------------------------------------------------

    if show_report:

        print("\nClassification Report:")
        print(
            classification_report(
                y_eval_data,
                y_pred,
                zero_division=0
            )
        )


    # --------------------------------------------------------
    # Confusion Matrix
    # --------------------------------------------------------

    if show_confusion_matrix:

        cm = confusion_matrix(
            y_eval_data,
            y_pred
        )

        plt.figure(figsize=(10, 8))

        disp = ConfusionMatrixDisplay(
            confusion_matrix=cm
        )

        disp.plot(
            xticks_rotation="vertical"
        )

        plt.title(
            f"Confusion Matrix — {model_name}"
        )

        plt.tight_layout()
        plt.show()


    # --------------------------------------------------------
    # Return Results
    # --------------------------------------------------------

    return {
        "Model": model_name,
        "Accuracy": accuracy,
        "Macro Precision": macro_precision,
        "Macro Recall": macro_recall,
        "Macro F1": macro_f1,
        "Weighted F1": weighted_f1,
        "Training Time (s)": train_time,
        "Prediction Time (s)": prediction_time,
        "y_true": y_eval_data,
        "y_pred": y_pred,
        "pipeline": pipeline
    }

In [15]:
# ============================================================
# 2. Benchmark Runner
# ============================================================

def run_benchmark(
    pipelines,
    X_train_data,
    y_train_data,
    X_eval_data,
    y_eval_data,
    show_report=False,
    show_confusion_matrix=False
):
    """
    Run all registered models using the same evaluation protocol.
    """

    results = []

    for model_name, pipeline in pipelines.items():

        result = evaluate_model(
            model_name=model_name,
            pipeline=pipeline,
            X_train_data=X_train_data,
            y_train_data=y_train_data,
            X_eval_data=X_eval_data,
            y_eval_data=y_eval_data,
            show_report=show_report,
            show_confusion_matrix=show_confusion_matrix
        )

        results.append(result)


    # --------------------------------------------------------
    # Create Benchmark Table
    # --------------------------------------------------------

    results_df = pd.DataFrame([
        {
            key: value
            for key, value in result.items()
            if key not in [
                "y_true",
                "y_pred",
                "pipeline"
            ]
        }
        for result in results
    ])

    results_df = results_df.sort_values(
        by="Macro F1",
        ascending=False
    ).reset_index(drop=True)

    return results, results_df

In [16]:
# ============================================================
# 3. Development Benchmark
# ============================================================

benchmark_results, benchmark_df = run_benchmark(
    pipelines=PIPELINES,

    X_train_data=X_dev,
    y_train_data=y_dev,

    X_eval_data=X_dev,
    y_eval_data=y_dev,

    show_report=False,
    show_confusion_matrix=False
)

======================================================================
MODEL: Logistic Regression
======================================================================

Training Time   : 113.27 seconds
Prediction Time : 0.48 seconds

Accuracy        : 0.8640
Macro Precision : 0.5441
Macro Recall    : 0.3171
Macro F1        : 0.3239
Weighted F1     : 0.8612

======================================================================
MODEL: Decision Tree
======================================================================

Training Time   : 10.76 seconds
Prediction Time : 0.26 seconds

Accuracy        : 0.9991
Macro Precision : 0.9986
Macro Recall    : 0.9908
Macro F1        : 0.9946
Weighted F1     : 0.9991

======================================================================
MODEL: Random Forest
======================================================================

Training Time   : 109.67 seconds
Prediction Time : 3.66 seconds

Accuracy        : 0.9991
Macro Precision : 0.9959
Macro Recall    : 0.9932
Macro F1        : 0.9945
Weighted F1     : 0.9991

======================================================================
MODEL: HistGradientBoosting
======================================================================

Training Time   : 11.15 seconds
Prediction Time : 1.39 seconds

Accuracy        : 0.9026
Macro Precision : 0.5716
Macro Recall    : 0.5432
Macro F1        : 0.5248
Weighted F1     : 0.9020

In [17]:
# ============================================================
# STEP 6: GROUP-AWARE DEVELOPMENT VALIDATION SPLIT
# ============================================================

from sklearn.model_selection import StratifiedGroupKFold


# ------------------------------------------------------------
# 1. Create feature groups for the development set
# ------------------------------------------------------------

groups_dev = pd.util.hash_pandas_object(
    X_dev,
    index=False
)


print("=" * 60)
print("DEVELOPMENT GROUP INFORMATION")
print("=" * 60)

print(f"Development samples : {len(X_dev):,}")
print(f"Unique feature groups: {groups_dev.nunique():,}")
print(
    f"Duplicate feature groups: "
    f"{len(groups_dev) - groups_dev.nunique():,}"
)

============================================================
DEVELOPMENT GROUP INFORMATION
============================================================
Development samples : 120,000
Unique feature groups: 119,889
Duplicate feature groups: 111

In [18]:
# ------------------------------------------------------------
# 2. Group-aware stratified split
# ------------------------------------------------------------

sgkf_dev = StratifiedGroupKFold(
    n_splits=5,
    shuffle=True,
    random_state=SEED
)


train_idx, val_idx = next(
    sgkf_dev.split(
        X_dev,
        y_dev,
        groups=groups_dev
    )
)


# ------------------------------------------------------------
# 3. Create development train/validation sets
# ------------------------------------------------------------

X_dev_train = X_dev.iloc[train_idx].copy()
X_dev_val = X_dev.iloc[val_idx].copy()

y_dev_train = y_dev.iloc[train_idx].copy()
y_dev_val = y_dev.iloc[val_idx].copy()

groups_dev_train = groups_dev.iloc[train_idx]
groups_dev_val = groups_dev.iloc[val_idx]

In [19]:
# ============================================================
# 4. VALIDATION SPLIT VERIFICATION
# ============================================================

print("\n" + "=" * 60)
print("DEVELOPMENT SPLIT")
print("=" * 60)

print(f"Training samples   : {len(X_dev_train):,}")
print(f"Validation samples : {len(X_dev_val):,}")


print("\nClass distribution:")
print(
    pd.DataFrame({
        "Train": y_dev_train.value_counts().sort_index(),
        "Validation": y_dev_val.value_counts().sort_index()
    })
)

============================================================
DEVELOPMENT SPLIT
============================================================
Training samples   : 96,002
Validation samples : 23,998

Class distribution:
       Train  Validation
Label
0      70550       17657
1        108          39
2        132          42
3       1420         318
4       9698        2409
5       8242        2074
6       1425         342
7       3780         944
8        570         152
9         77          21

In [20]:
# ------------------------------------------------------------
# 5. Verify zero feature-group overlap
# ------------------------------------------------------------

group_overlap = set(
    groups_dev_train
).intersection(
    set(groups_dev_val)
)


print("\n" + "=" * 60)
print("GROUP LEAKAGE CHECK")
print("=" * 60)

print(
    f"Overlapping feature groups : {len(group_overlap)}"
)

============================================================
GROUP LEAKAGE CHECK
============================================================
Overlapping feature groups : 0

In [21]:
# ============================================================
# STEP 6.4: PROPER DEVELOPMENT BENCHMARK
# ============================================================

dev_results, dev_results_df = run_benchmark(
    pipelines=PIPELINES,

    X_train_data=X_dev_train,
    y_train_data=y_dev_train,

    X_eval_data=X_dev_val,
    y_eval_data=y_dev_val,

    show_report=False,
    show_confusion_matrix=False
)

======================================================================
MODEL: Logistic Regression
======================================================================

Training Time   : 96.13 seconds
Prediction Time : 0.06 seconds

Accuracy        : 0.8673
Macro Precision : 0.5194
Macro Recall    : 0.3179
Macro F1        : 0.3222
Weighted F1     : 0.8642

======================================================================
MODEL: Decision Tree
======================================================================

Training Time   : 10.17 seconds
Prediction Time : 0.05 seconds

Accuracy        : 0.8816
Macro Precision : 0.5270
Macro Recall    : 0.5064
Macro F1        : 0.5152
Weighted F1     : 0.8812

======================================================================
MODEL: Random Forest
======================================================================

Training Time   : 90.81 seconds
Prediction Time : 1.10 seconds

Accuracy        : 0.9037
Macro Precision : 0.6280
Macro Recall    : 0.4986
Macro F1        : 0.5383
Weighted F1     : 0.9018

======================================================================
MODEL: HistGradientBoosting
======================================================================

Training Time   : 14.66 seconds
Prediction Time : 0.54 seconds

Accuracy        : 0.8964
Macro Precision : 0.5043
Macro Recall    : 0.4528
Macro F1        : 0.4531
Weighted F1     : 0.8964

In [22]:


# ------------------------------------------------------------
# Sorted Model Comparison
# ------------------------------------------------------------

dev_results_df[
    [
        "Model",
        "Accuracy",
        "Macro Precision",
        "Macro Recall",
        "Macro F1",
        "Weighted F1",
        "Training Time (s)",
        "Prediction Time (s)"
    ]
]

,Model,Accuracy,Macro Precision,Macro Recall,Macro F1,Weighted F1,Training Time (s),Prediction Time (s)
0,Random Forest,0.903659,0.627959,0.498618,0.538330,0.901804,90.806255,1.097115
1,Decision Tree,0.881573,0.526958,0.506445,0.515201,0.881214,10.169917,0.051175
2,HistGradientBoosting,0.896366,0.504336,0.452758,0.453139,0.896364,14.658423,0.538044
3,Logistic Regression,0.867281,0.519392,0.317857,0.322221,0.864208,96.134933,0.061533

In [23]:
# ============================================================
# STEP 6.5: PER-CLASS BASELINE ANALYSIS
# ============================================================

label_names = {
    0: "Benign",
    1: "Analysis",
    2: "Backdoor",
    3: "DoS",
    4: "Exploits",
    5: "Fuzzers",
    6: "Generic",
    7: "Reconnaissance",
    8: "Shellcode",
    9: "Worms"
}


for result in dev_results:

    print("\n" + "=" * 80)
    print(f"MODEL: {result['Model']}")
    print("=" * 80)

    report = classification_report(
        result["y_true"],
        result["y_pred"],
        labels=list(label_names.keys()),
        target_names=list(label_names.values()),
        output_dict=True,
        zero_division=0
    )

    class_report = pd.DataFrame(report).T

    class_report = class_report.loc[
        list(label_names.values())
    ]

    print(
        class_report[
            [
                "precision",
                "recall",
                "f1-score",
                "support"
            ]
        ].round(4)
    )

================================================================================
MODEL: Logistic Regression
================================================================================
                precision  recall  f1-score  support
Benign             0.9951  0.9626    0.9786  17657.0
Analysis           0.0000  0.0000    0.0000     39.0
Backdoor           1.0000  0.0238    0.0465     42.0
DoS                0.4286  0.0094    0.0185    318.0
Exploits           0.7000  0.6480    0.6730   2409.0
Fuzzers            0.4462  0.8616    0.5879   2074.0
Generic            0.6439  0.2485    0.3586    342.0
Reconnaissance     0.7135  0.3983    0.5112    944.0
Shellcode          0.2667  0.0263    0.0479    152.0
Worms              0.0000  0.0000    0.0000     21.0

================================================================================
MODEL: Decision Tree
================================================================================
                precision  recall  f1-score  support
Benign             0.9737  0.9767    0.9752  17657.0
Analysis           0.2821  0.2821    0.2821     39.0
Backdoor           0.5625  0.4286    0.4865     42.0
DoS                0.2714  0.2987    0.2844    318.0
Exploits           0.7000  0.6924    0.6962   2409.0
Fuzzers            0.6428  0.6369    0.6399   2074.0
Generic            0.6341  0.6637    0.6486    342.0
Reconnaissance     0.5839  0.5678    0.5757    944.0
Shellcode          0.2074  0.1842    0.1951    152.0
Worms              0.4118  0.3333    0.3684     21.0

================================================================================
MODEL: Random Forest
================================================================================
                precision  recall  f1-score  support
Benign             0.9861  0.9758    0.9810  17657.0
Analysis           0.2381  0.1282    0.1667     39.0
Backdoor           0.9200  0.5476    0.6866     42.0
DoS                0.6061  0.2516    0.3556    318.0
Exploits           0.7434  0.7879    0.7650   2409.0
Fuzzers            0.6265  0.7989    0.7023   2074.0
Generic            0.7957  0.6491    0.7150    342.0
Reconnaissance     0.6809  0.5742    0.6230    944.0
Shellcode          0.3971  0.1776    0.2455    152.0
Worms              0.2857  0.0952    0.1429     21.0

================================================================================
MODEL: HistGradientBoosting
================================================================================
                precision  recall  f1-score  support
Benign             0.9871  0.9748    0.9809  17657.0
Analysis           0.0656  0.2051    0.0994     39.0
Backdoor           0.2083  0.3571    0.2632     42.0
DoS                0.5106  0.1509    0.2330    318.0
Exploits           0.7750  0.7323    0.7530   2409.0
Fuzzers            0.5846  0.8544    0.6942   2074.0
Generic            0.7252  0.5556    0.6291    342.0
Reconnaissance     0.8535  0.5000    0.6306    944.0
Shellcode          0.3333  0.1974    0.2479    152.0
Worms              0.0000  0.0000    0.0000     21.0

In [24]:
# ============================================================
# STEP 7 — CLASS-WEIGHTED MODEL REGISTRY
# ============================================================

WEIGHTED_MODEL_REGISTRY = {

    "Logistic Regression (Balanced)": {
        "model": LogisticRegression(
            max_iter=1000,
            class_weight="balanced",
            random_state=SEED
        ),
        "scale": True,
        "sampler": None
    },

    "Decision Tree (Balanced)": {
        "model": DecisionTreeClassifier(
            class_weight="balanced",
            random_state=SEED
        ),
        "scale": False,
        "sampler": None
    },

    "Random Forest (Balanced)": {
        "model": RandomForestClassifier(
            n_estimators=200,
            class_weight="balanced",
            random_state=SEED,
            n_jobs=-1
        ),
        "scale": False,
        "sampler": None

    }
}

In [25]:
# ============================================================
# BUILD WEIGHTED PIPELINES
# ============================================================

WEIGHTED_PIPELINES = {}

for model_name, config in WEIGHTED_MODEL_REGISTRY.items():

    WEIGHTED_PIPELINES[model_name] = build_pipeline(
        model=config["model"],
        num_cols=num_cols,
        cat_cols=cat_cols,
        scale=config["scale"],
        sampler=config["sampler"]
    )

In [26]:
# ============================================================
# RUN CLASS-WEIGHTED BENCHMARK
# ============================================================

weighted_results, weighted_results_df = run_benchmark(
    pipelines=WEIGHTED_PIPELINES,
    X_train_data=X_dev_train,
    y_train_data=y_dev_train,
    X_eval_data=X_dev_val,
    y_eval_data=y_dev_val,
    show_report=False,
    show_confusion_matrix=False
)

weighted_results_df

======================================================================
MODEL: Logistic Regression (Balanced)
======================================================================

Training Time   : 225.51 seconds
Prediction Time : 0.08 seconds

Accuracy        : 0.8192
Macro Precision : 0.3683
Macro Recall    : 0.5928
Macro F1        : 0.3633
Weighted F1     : 0.8423

======================================================================
MODEL: Decision Tree (Balanced)
======================================================================

Training Time   : 6.47 seconds
Prediction Time : 0.05 seconds

Accuracy        : 0.8791
Macro Precision : 0.5097
Macro Recall    : 0.5007
Macro F1        : 0.5043
Weighted F1     : 0.8792

======================================================================
MODEL: Random Forest (Balanced)
======================================================================

Training Time   : 68.81 seconds
Prediction Time : 1.60 seconds

Accuracy        : 0.9047
Macro Precision : 0.6569
Macro Recall    : 0.5081
Macro F1        : 0.5524
Weighted F1     : 0.9029

,Model,Accuracy,Macro Precision,Macro Recall,Macro F1,Weighted F1,Training Time (s),Prediction Time (s)
0,Random Forest (Balanced),0.904742,0.656933,0.508097,0.552423,0.902885,68.814152,1.602659
1,Decision Tree (Balanced),0.879073,0.509693,0.500691,0.504286,0.879218,6.468021,0.052161
2,Logistic Regression (Balanced),0.819193,0.368254,0.592768,0.363281,0.842274,225.506780,0.082606

In [27]:
# ============================================================
# BASELINE vs WEIGHTED COMPARISON
# ============================================================

baseline_summary = dev_results_df[
    [
        "Model",
        "Accuracy",
        "Macro Precision",
        "Macro Recall",
        "Macro F1",
        "Weighted F1"
    ]
].copy()

weighted_summary = weighted_results_df[
    [
        "Model",
        "Accuracy",
        "Macro Precision",
        "Macro Recall",
        "Macro F1",
        "Weighted F1"
    ]
].copy()

comparison_df = pd.concat(
    [baseline_summary, weighted_summary],
    ignore_index=True
)

comparison_df.sort_values(
    by="Macro F1",
    ascending=False
).reset_index(drop=True)

,Model,Accuracy,Macro Precision,Macro Recall,Macro F1,Weighted F1
0,Random Forest (Balanced),0.904742,0.656933,0.508097,0.552423,0.902885
1,Random Forest,0.903659,0.627959,0.498618,0.538330,0.901804
2,Decision Tree,0.881573,0.526958,0.506445,0.515201,0.881214
3,Decision Tree (Balanced),0.879073,0.509693,0.500691,0.504286,0.879218
4,HistGradientBoosting,0.896366,0.504336,0.452758,0.453139,0.896364
5,Logistic Regression (Balanced),0.819193,0.368254,0.592768,0.363281,0.842274
6,Logistic Regression,0.867281,0.519392,0.317857,0.322221,0.864208

In [28]:
# ============================================================
# PER-CLASS RESULTS FOR WEIGHTED MODELS
# ============================================================

for result in weighted_results:

    print("\n" + "=" * 70)
    print(result["Model"])
    print("=" * 70)

    print(
        classification_report(
            result["y_true"],
            result["y_pred"],
            zero_division=0
        )
    )

======================================================================
Logistic Regression (Balanced)
======================================================================
              precision    recall  f1-score   support

           0       1.00      0.96      0.98     17657
           1       0.13      1.00      0.23        39
           2       0.09      0.67      0.16        42
           3       0.16      0.10      0.12       318
           4       0.86      0.39      0.54      2409
           5       0.55      0.38      0.45      2074
           6       0.35      0.55      0.43       342
           7       0.41      0.66      0.51       944
           8       0.12      0.55      0.19       152
           9       0.01      0.67      0.03        21

    accuracy                           0.82     23998
   macro avg       0.37      0.59      0.36     23998
weighted avg       0.89      0.82      0.84     23998


======================================================================
Decision Tree (Balanced)
======================================================================
              precision    recall  f1-score   support

           0       0.97      0.97      0.97     17657
           1       0.36      0.31      0.33        39
           2       0.48      0.48      0.48        42
           3       0.25      0.30      0.27       318
           4       0.71      0.69      0.70      2409
           5       0.63      0.64      0.63      2074
           6       0.62      0.65      0.63       342
           7       0.58      0.57      0.58       944
           8       0.20      0.17      0.18       152
           9       0.29      0.24      0.26        21

    accuracy                           0.88     23998
   macro avg       0.51      0.50      0.50     23998
weighted avg       0.88      0.88      0.88     23998


======================================================================
Random Forest (Balanced)
======================================================================
              precision    recall  f1-score   support

           0       0.99      0.98      0.98     17657
           1       0.25      0.15      0.19        39
           2       0.92      0.52      0.67        42
           3       0.62      0.25      0.36       318
           4       0.74      0.79      0.77      2409
           5       0.63      0.81      0.71      2074
           6       0.81      0.65      0.72       342
           7       0.68      0.57      0.62       944
           8       0.43      0.16      0.23       152
           9       0.50      0.19      0.28        21

    accuracy                           0.90     23998
   macro avg       0.66      0.51      0.55     23998
weighted avg       0.91      0.90      0.90     23998

In [29]:
# ============================================================
# STEP 8 — SMOTE MODEL REGISTRY
# ============================================================

SMOTE_MODEL_REGISTRY = {

    "Logistic Regression (SMOTE)": {
        "model": LogisticRegression(
            max_iter=1000,
            random_state=SEED
        ),
        "scale": True,
        "sampler": SMOTE(
            random_state=SEED,
            k_neighbors=3
        )
    },

    "Decision Tree (SMOTE)": {
        "model": DecisionTreeClassifier(
            random_state=SEED
        ),
        "scale": False,
        "sampler": SMOTE(
            random_state=SEED,
            k_neighbors=3
        )
    },

    "Random Forest (SMOTE)": {
        "model": RandomForestClassifier(
            n_estimators=200,
            random_state=SEED,
            n_jobs=-1
        ),
        "scale": False,
        "sampler": SMOTE(
            random_state=SEED,
            k_neighbors=3
        )
    }
}

In [34]:
# ============================================================
# BUILD SMOTE PIPELINES
# ============================================================

SMOTE_PIPELINES = {}

for model_name, config in SMOTE_MODEL_REGISTRY.items():

    SMOTE_PIPELINES[model_name] = build_pipeline(
        model=config["model"],
        num_cols=num_cols,
        cat_cols=cat_cols,
        scale=config["scale"],
        sampler=config["sampler"]
    )

In [35]:
# ============================================================
# RUN SMOTE BENCHMARK
# ============================================================

smote_results, smote_results_df = run_benchmark(
    pipelines=SMOTE_PIPELINES,
    X_train_data=X_dev_train,
    y_train_data=y_dev_train,
    X_eval_data=X_dev_val,
    y_eval_data=y_dev_val,
    show_report=False,
    show_confusion_matrix=False
)

smote_results_df

======================================================================
MODEL: Logistic Regression (SMOTE)
======================================================================

Training Time   : 841.34 seconds
Prediction Time : 0.15 seconds

Accuracy        : 0.8264
Macro Precision : 0.3765
Macro Recall    : 0.5992
Macro F1        : 0.3770
Weighted F1     : 0.8490

======================================================================
MODEL: Decision Tree (SMOTE)
======================================================================

Training Time   : 154.19 seconds
Prediction Time : 0.08 seconds

Accuracy        : 0.8723
Macro Precision : 0.4392
Macro Recall    : 0.4725
Macro F1        : 0.4509
Weighted F1     : 0.8760

======================================================================
MODEL: Random Forest (SMOTE)
======================================================================

Training Time   : 1648.12 seconds
Prediction Time : 1.39 seconds

Accuracy        : 0.8911
Macro Precision : 0.5052
Macro Recall    : 0.5230
Macro F1        : 0.5102
Weighted F1     : 0.8948

,Model,Accuracy,Macro Precision,Macro Recall,Macro F1,Weighted F1,Training Time (s),Prediction Time (s)
0,Random Forest (SMOTE),0.891074,0.505172,0.523031,0.510238,0.894772,1648.116062,1.387479
1,Decision Tree (SMOTE),0.872281,0.439174,0.472484,0.450857,0.875964,154.188967,0.082578
2,Logistic Regression (SMOTE),0.826444,0.376514,0.599208,0.377040,0.849025,841.335633,0.149096

In [36]:
# ============================================================
# COMPLETE IMBALANCE STRATEGY COMPARISON
# ============================================================

baseline_summary = dev_results_df[
    [
        "Model",
        "Accuracy",
        "Macro Precision",
        "Macro Recall",
        "Macro F1",
        "Weighted F1"
    ]
].copy()

weighted_summary = weighted_results_df[
    [
        "Model",
        "Accuracy",
        "Macro Precision",
        "Macro Recall",
        "Macro F1",
        "Weighted F1"
    ]
].copy()

smote_summary = smote_results_df[
    [
        "Model",
        "Accuracy",
        "Macro Precision",
        "Macro Recall",
        "Macro F1",
        "Weighted F1"
    ]
].copy()

imbalance_comparison_df = pd.concat(
    [
        baseline_summary,
        weighted_summary,
        smote_summary
    ],
    ignore_index=True
)

imbalance_comparison_df = imbalance_comparison_df.sort_values(
    by="Macro F1",
    ascending=False
).reset_index(drop=True)

imbalance_comparison_df

,Model,Accuracy,Macro Precision,Macro Recall,Macro F1,Weighted F1
0,Random Forest (Balanced),0.904742,0.656933,0.508097,0.552423,0.902885
1,Random Forest,0.903659,0.627959,0.498618,0.538330,0.901804
2,Decision Tree,0.881573,0.526958,0.506445,0.515201,0.881214
3,Random Forest (SMOTE),0.891074,0.505172,0.523031,0.510238,0.894772
4,Decision Tree (Balanced),0.879073,0.509693,0.500691,0.504286,0.879218
5,HistGradientBoosting,0.896366,0.504336,0.452758,0.453139,0.896364
6,Decision Tree (SMOTE),0.872281,0.439174,0.472484,0.450857,0.875964
7,Logistic Regression (SMOTE),0.826444,0.376514,0.599208,0.377040,0.849025
8,Logistic Regression (Balanced),0.819193,0.368254,0.592768,0.363281,0.842274
9,Logistic Regression,0.867281,0.519392,0.317857,0.322221,0.864208

In [37]:
# ============================================================
# PER-CLASS RESULTS — SMOTE
# ============================================================

for result in smote_results:

    print("\n" + "=" * 70)
    print(result["Model"])
    print("=" * 70)

    print(
        classification_report(
            result["y_true"],
            result["y_pred"],
            zero_division=0
        )
    )

======================================================================
Logistic Regression (SMOTE)
======================================================================
              precision    recall  f1-score   support

           0       1.00      0.96      0.98     17657
           1       0.15      1.00      0.25        39
           2       0.10      0.67      0.18        42
           3       0.17      0.11      0.13       318
           4       0.87      0.40      0.55      2409
           5       0.55      0.46      0.50      2074
           6       0.34      0.56      0.42       342
           7       0.45      0.63      0.53       944
           8       0.13      0.55      0.21       152
           9       0.01      0.67      0.03        21

    accuracy                           0.83     23998
   macro avg       0.38      0.60      0.38     23998
weighted avg       0.90      0.83      0.85     23998


======================================================================
Decision Tree (SMOTE)
======================================================================
              precision    recall  f1-score   support

           0       0.98      0.97      0.98     17657
           1       0.24      0.18      0.21        39
           2       0.39      0.45      0.42        42
           3       0.18      0.27      0.22       318
           4       0.70      0.67      0.68      2409
           5       0.62      0.60      0.61      2074
           6       0.51      0.62      0.56       342
           7       0.56      0.58      0.57       944
           8       0.10      0.14      0.12       152
           9       0.11      0.24      0.15        21

    accuracy                           0.87     23998
   macro avg       0.44      0.47      0.45     23998
weighted avg       0.88      0.87      0.88     23998


======================================================================
Random Forest (SMOTE)
======================================================================
              precision    recall  f1-score   support

           0       0.99      0.97      0.98     17657
           1       0.29      0.21      0.24        39
           2       0.62      0.57      0.59        42
           3       0.29      0.32      0.30       318
           4       0.74      0.73      0.74      2409
           5       0.63      0.73      0.68      2074
           6       0.63      0.64      0.64       342
           7       0.58      0.60      0.59       944
           8       0.17      0.22      0.19       152
           9       0.11      0.24      0.15        21

    accuracy                           0.89     23998
   macro avg       0.51      0.52      0.51     23998
weighted avg       0.90      0.89      0.89     23998

In [44]:
# ============================================================
# STEP 9 — ADVANCED MODELS
# IMPORTS
# ============================================================

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

from imblearn.ensemble import BalancedRandomForestClassifier

# ============================================================
# ADVANCED MODEL REGISTRY
# ============================================================

ADVANCED_MODEL_REGISTRY = {

    "XGBoost": {
        "model": XGBClassifier(
            n_estimators=300,
            learning_rate=0.05,
            max_depth=6,
            subsample=0.8,
            colsample_bytree=0.8,
            objective="multi:softmax",
            eval_metric="mlogloss",
            random_state=SEED,
            n_jobs=-1
        ),
        "scale": False,
        "sampler": None
    },

    "LightGBM": {
        "model": LGBMClassifier(
            n_estimators=300,
            learning_rate=0.05,
            max_depth=-1,
            num_leaves=31,
            subsample=0.8,
            colsample_bytree=0.8,
            random_state=SEED,
            n_jobs=-1,
            verbosity=-1
        ),
        "scale": False,
        "sampler": None
    },

    "CatBoost": {
        "model": CatBoostClassifier(
            iterations=300,
            learning_rate=0.05,
            depth=6,
            loss_function="MultiClass",
            random_seed=SEED,
            verbose=False,
            thread_count=-1
        ),
        "scale": False,
        "sampler": None
    },

    "Balanced Random Forest": {
        "model": BalancedRandomForestClassifier(
            n_estimators=200,
            random_state=SEED,
            n_jobs=-1
        ),
        "scale": False,
        "sampler": None
    }
}

In [45]:
# ============================================================
# BUILD ADVANCED PIPELINES
# ============================================================

ADVANCED_PIPELINES = {}

for model_name, config in ADVANCED_MODEL_REGISTRY.items():

    ADVANCED_PIPELINES[model_name] = build_pipeline(
        model=config["model"],
        num_cols=num_cols,
        cat_cols=cat_cols,
        scale=config["scale"],
        sampler=config["sampler"]
    )

In [46]:
# ============================================================
# STEP 9.3 — ADVANCED MODEL BENCHMARK
# ============================================================

advanced_results, advanced_results_df = run_benchmark(
    pipelines=ADVANCED_PIPELINES,
    X_train_data=X_dev_train,
    y_train_data=y_dev_train,
    X_eval_data=X_dev_val,
    y_eval_data=y_dev_val,
    show_report=False,
    show_confusion_matrix=False
)

advanced_results_df

======================================================================
MODEL: XGBoost
======================================================================

Training Time   : 129.45 seconds
Prediction Time : 1.64 seconds

Accuracy        : 0.9083
Macro Precision : 0.7130
Macro Recall    : 0.4863
Macro F1        : 0.5385
Weighted F1     : 0.9056

======================================================================
MODEL: LightGBM
======================================================================

Training Time   : 87.24 seconds
Prediction Time : 4.65 seconds

Accuracy        : 0.8947
Macro Precision : 0.4878
Macro Recall    : 0.4610
Macro F1        : 0.4618
Weighted F1     : 0.8941

======================================================================
MODEL: CatBoost
======================================================================

Training Time   : 295.94 seconds
Prediction Time : 0.20 seconds

Accuracy        : 0.9001
Macro Precision : 0.5669
Macro Recall    : 0.3871
Macro F1        : 0.4039
Weighted F1     : 0.8948

======================================================================
MODEL: Balanced Random Forest
======================================================================

Training Time   : 6.77 seconds
Prediction Time : 0.99 seconds

Accuracy        : 0.8462
Macro Precision : 0.4138
Macro Recall    : 0.6543
Macro F1        : 0.4307
Weighted F1     : 0.8659

,Model,Accuracy,Macro Precision,Macro Recall,Macro F1,Weighted F1,Training Time (s),Prediction Time (s)
0,XGBoost,0.908284,0.712953,0.486296,0.538460,0.905642,129.449561,1.635107
1,LightGBM,0.894658,0.487781,0.460968,0.461756,0.894130,87.237561,4.649495
2,Balanced Random Forest,0.846154,0.413796,0.654325,0.430703,0.865938,6.766607,0.987138
3,CatBoost,0.900117,0.566875,0.387150,0.403869,0.894848,295.935392,0.204439

In [47]:
# ============================================================
# COMPLETE DEVELOPMENT LEADERBOARD
# ============================================================

baseline_summary = dev_results_df[
    [
        "Model",
        "Accuracy",
        "Macro Precision",
        "Macro Recall",
        "Macro F1",
        "Weighted F1",
        "Training Time (s)",
        "Prediction Time (s)"
    ]
].copy()

weighted_summary = weighted_results_df[
    [
        "Model",
        "Accuracy",
        "Macro Precision",
        "Macro Recall",
        "Macro F1",
        "Weighted F1",
        "Training Time (s)",
        "Prediction Time (s)"
    ]
].copy()

smote_summary = smote_results_df[
    [
        "Model",
        "Accuracy",
        "Macro Precision",
        "Macro Recall",
        "Macro F1",
        "Weighted F1",
        "Training Time (s)",
        "Prediction Time (s)"
    ]
].copy()

advanced_summary = advanced_results_df[
    [
        "Model",
        "Accuracy",
        "Macro Precision",
        "Macro Recall",
        "Macro F1",
        "Weighted F1",
        "Training Time (s)",
        "Prediction Time (s)"
    ]
].copy()

complete_leaderboard = pd.concat(
    [
        baseline_summary,
        weighted_summary,
        smote_summary,
        advanced_summary
    ],
    ignore_index=True
)

complete_leaderboard = complete_leaderboard.sort_values(
    by="Macro F1",
    ascending=False
).reset_index(drop=True)

complete_leaderboard

,Model,Accuracy,Macro Precision,Macro Recall,Macro F1,Weighted F1,Training Time (s),Prediction Time (s)
0,Random Forest (Balanced),0.904742,0.656933,0.508097,0.552423,0.902885,68.814152,1.602659
1,XGBoost,0.908284,0.712953,0.486296,0.538460,0.905642,129.449561,1.635107
2,Random Forest,0.903659,0.627959,0.498618,0.538330,0.901804,90.806255,1.097115
3,Decision Tree,0.881573,0.526958,0.506445,0.515201,0.881214,10.169917,0.051175
4,Random Forest (SMOTE),0.891074,0.505172,0.523031,0.510238,0.894772,1648.116062,1.387479
5,Decision Tree (Balanced),0.879073,0.509693,0.500691,0.504286,0.879218,6.468021,0.052161
6,LightGBM,0.894658,0.487781,0.460968,0.461756,0.894130,87.237561,4.649495
7,HistGradientBoosting,0.896366,0.504336,0.452758,0.453139,0.896364,14.658423,0.538044
8,Decision Tree (SMOTE),0.872281,0.439174,0.472484,0.450857,0.875964,154.188967,0.082578
9,Balanced Random Forest,0.846154,0.413796,0.654325,0.430703,0.865938,6.766607,0.987138
10,CatBoost,0.900117,0.566875,0.387150,0.403869,0.894848,295.935392,0.204439
11,Logistic Regression (SMOTE),0.826444,0.376514,0.599208,0.377040,0.849025,841.335633,0.149096
12,Logistic Regression (Balanced),0.819193,0.368254,0.592768,0.363281,0.842274,225.506780,0.082606
13,Logistic Regression,0.867281,0.519392,0.317857,0.322221,0.864208,96.134933,0.061533

In [48]:
# ============================================================
# STEP 9.5 — PER-CLASS ANALYSIS
# ============================================================

for result in advanced_results:

    print("\n" + "=" * 70)
    print(result["Model"])
    print("=" * 70)

    print(
        classification_report(
            result["y_true"],
            result["y_pred"],
            zero_division=0
        )
    )

======================================================================
XGBoost
======================================================================
              precision    recall  f1-score   support

           0       0.99      0.98      0.98     17657
           1       0.33      0.10      0.16        39
           2       0.95      0.43      0.59        42
           3       0.70      0.18      0.28       318
           4       0.77      0.78      0.77      2409
           5       0.59      0.91      0.72      2074
           6       0.82      0.61      0.70       342
           7       0.81      0.53      0.64       944
           8       0.60      0.16      0.26       152
           9       0.57      0.19      0.29        21

    accuracy                           0.91     23998
   macro avg       0.71      0.49      0.54     23998
weighted avg       0.92      0.91      0.91     23998


======================================================================
LightGBM
======================================================================
              precision    recall  f1-score   support

           0       0.99      0.97      0.98     17657
           1       0.19      0.26      0.22        39
           2       0.27      0.38      0.32        42
           3       0.36      0.20      0.26       318
           4       0.76      0.70      0.73      2409
           5       0.59      0.88      0.71      2074
           6       0.58      0.49      0.53       342
           7       0.80      0.51      0.62       944
           8       0.32      0.18      0.23       152
           9       0.02      0.05      0.03        21

    accuracy                           0.89     23998
   macro avg       0.49      0.46      0.46     23998
weighted avg       0.90      0.89      0.89     23998


======================================================================
CatBoost
======================================================================
              precision    recall  f1-score   support

           0       0.99      0.97      0.98     17657
           1       0.00      0.00      0.00        39
           2       0.80      0.10      0.17        42
           3       0.62      0.05      0.09       318
           4       0.73      0.78      0.75      2409
           5       0.57      0.89      0.70      2074
           6       0.73      0.49      0.59       342
           7       0.82      0.52      0.64       944
           8       0.40      0.07      0.11       152
           9       0.00      0.00      0.00        21

    accuracy                           0.90     23998
   macro avg       0.57      0.39      0.40     23998
weighted avg       0.91      0.90      0.89     23998


======================================================================
Balanced Random Forest
======================================================================
              precision    recall  f1-score   support

           0       1.00      0.96      0.98     17657
           1       0.25      1.00      0.39        39
           2       0.08      0.74      0.15        42
           3       0.21      0.29      0.24       318
           4       0.90      0.44      0.59      2409
           5       0.60      0.58      0.59      2074
           6       0.43      0.65      0.52       342
           7       0.51      0.67      0.58       944
           8       0.14      0.56      0.22       152
           9       0.03      0.67      0.05        21

    accuracy                           0.85     23998
   macro avg       0.41      0.65      0.43     23998
weighted avg       0.91      0.85      0.87     23998

In [49]:
CV_PIPELINES = {
    "Random Forest (Balanced)": WEIGHTED_PIPELINES["Random Forest (Balanced)"],
    "XGBoost": ADVANCED_PIPELINES["XGBoost"],
    "Random Forest": PIPELINES["Random Forest"],
    "Decision Tree": PIPELINES["Decision Tree"]
}

cv = StratifiedGroupKFold(
    n_splits=5,
    shuffle=True,
    random_state=SEED
)

In [50]:
def cross_validate_group_aware(
    model_name,
    pipeline,
    X_data,
    y_data,
    groups,
    cv
):
    fold_results = []

    print("\n" + "=" * 70)
    print(f"MODEL: {model_name}")
    print("=" * 70)

    for fold, (train_idx, val_idx) in enumerate(
        cv.split(X_data, y_data, groups=groups),
        start=1
    ):
        X_train_fold = X_data.iloc[train_idx]
        X_val_fold = X_data.iloc[val_idx]

        y_train_fold = y_data.iloc[train_idx]
        y_val_fold = y_data.iloc[val_idx]

        # Fresh unfitted pipeline for every fold
        fold_pipeline = clone(pipeline)

        start_train = time.perf_counter()

        fold_pipeline.fit(
            X_train_fold,
            y_train_fold
        )

        train_time = time.perf_counter() - start_train

        start_predict = time.perf_counter()

        y_pred = fold_pipeline.predict(X_val_fold)

        prediction_time = time.perf_counter() - start_predict

        accuracy = accuracy_score(
            y_val_fold,
            y_pred
        )

        macro_precision = precision_score(
            y_val_fold,
            y_pred,
            average="macro",
            zero_division=0
        )

        macro_recall = recall_score(
            y_val_fold,
            y_pred,
            average="macro",
            zero_division=0
        )

        macro_f1 = f1_score(
            y_val_fold,
            y_pred,
            average="macro",
            zero_division=0
        )

        weighted_f1 = f1_score(
            y_val_fold,
            y_pred,
            average="weighted",
            zero_division=0
        )

        fold_results.append({
            "Model": model_name,
            "Fold": fold,
            "Accuracy": accuracy,
            "Macro Precision": macro_precision,
            "Macro Recall": macro_recall,
            "Macro F1": macro_f1,
            "Weighted F1": weighted_f1,
            "Training Time (s)": train_time,
            "Prediction Time (s)": prediction_time
        })

        print(
            f"Fold {fold} | "
            f"Macro F1: {macro_f1:.4f} | "
            f"Macro Recall: {macro_recall:.4f} | "
            f"Accuracy: {accuracy:.4f}"
        )

    return pd.DataFrame(fold_results)

In [52]:
from sklearn.base import clone
cv_results_list = []

for model_name, pipeline in CV_PIPELINES.items():

    model_cv_results = cross_validate_group_aware(
        model_name=model_name,
        pipeline=pipeline,
        X_data=X_dev,
        y_data=y_dev,
        groups=groups_dev,
        cv=cv
    )

    cv_results_list.append(model_cv_results)

cv_results_df = pd.concat(
    cv_results_list,
    ignore_index=True
)

======================================================================
MODEL: Random Forest (Balanced)
======================================================================
Fold 1 | Macro F1: 0.5524 | Macro Recall: 0.5081 | Accuracy: 0.9047
Fold 2 | Macro F1: 0.5535 | Macro Recall: 0.5102 | Accuracy: 0.9038
Fold 3 | Macro F1: 0.5457 | Macro Recall: 0.5078 | Accuracy: 0.9023
Fold 4 | Macro F1: 0.5193 | Macro Recall: 0.4893 | Accuracy: 0.9010
Fold 5 | Macro F1: 0.5204 | Macro Recall: 0.4848 | Accuracy: 0.8985

======================================================================
MODEL: XGBoost
======================================================================
Fold 1 | Macro F1: 0.5385 | Macro Recall: 0.4863 | Accuracy: 0.9083
Fold 2 | Macro F1: 0.5307 | Macro Recall: 0.4828 | Accuracy: 0.9067
Fold 3 | Macro F1: 0.5331 | Macro Recall: 0.4971 | Accuracy: 0.9062
Fold 4 | Macro F1: 0.5182 | Macro Recall: 0.4820 | Accuracy: 0.9073
Fold 5 | Macro F1: 0.5162 | Macro Recall: 0.4768 | Accuracy: 0.9054

======================================================================
MODEL: Random Forest
======================================================================
Fold 1 | Macro F1: 0.5383 | Macro Recall: 0.4986 | Accuracy: 0.9037
Fold 2 | Macro F1: 0.5352 | Macro Recall: 0.4954 | Accuracy: 0.9031
Fold 3 | Macro F1: 0.5263 | Macro Recall: 0.4886 | Accuracy: 0.9017
Fold 4 | Macro F1: 0.5336 | Macro Recall: 0.5019 | Accuracy: 0.9024
Fold 5 | Macro F1: 0.4906 | Macro Recall: 0.4592 | Accuracy: 0.8993

======================================================================
MODEL: Decision Tree
======================================================================
Fold 1 | Macro F1: 0.5152 | Macro Recall: 0.5064 | Accuracy: 0.8816
Fold 2 | Macro F1: 0.4887 | Macro Recall: 0.4931 | Accuracy: 0.8804
Fold 3 | Macro F1: 0.4855 | Macro Recall: 0.4999 | Accuracy: 0.8791
Fold 4 | Macro F1: 0.4623 | Macro Recall: 0.4613 | Accuracy: 0.8793
Fold 5 | Macro F1: 0.4776 | Macro Recall: 0.4763 | Accuracy: 0.8791

In [54]:
CV_SUMMARY = (
    cv_results_df
    .groupby("Model")
    .agg(
        Accuracy_Mean=("Accuracy", "mean"),
        Accuracy_STD=("Accuracy", "std"),

        Macro_Precision_Mean=("Macro Precision", "mean"),
        Macro_Precision_STD=("Macro Precision", "std"),

        Macro_Recall_Mean=("Macro Recall", "mean"),
        Macro_Recall_STD=("Macro Recall", "std"),

        Macro_F1_Mean=("Macro F1", "mean"),
        Macro_F1_STD=("Macro F1", "std"),

        Weighted_F1_Mean=("Weighted F1", "mean"),
        Weighted_F1_STD=("Weighted F1", "std"),

        Training_Time_Mean=("Training Time (s)", "mean"),
        Prediction_Time_Mean=("Prediction Time (s)", "mean")
    )
    .sort_values(
        "Macro_F1_Mean",
        ascending=False
    )
    .reset_index()
)

CV_SUMMARY

,Model,Accuracy_Mean,Accuracy_STD,Macro_Precision_Mean,Macro_Precision_STD,Macro_Recall_Mean,Macro_Recall_STD,Macro_F1_Mean,Macro_F1_STD,Weighted_F1_Mean,Weighted_F1_STD,Training_Time_Mean,Prediction_Time_Mean
0,Random Forest (Balanced),0.902075,0.002453,0.631411,0.042589,0.500049,0.012011,0.538268,0.017088,0.900353,0.002363,60.337805,1.557388
1,XGBoost,0.906767,0.001094,0.668835,0.055933,0.484994,0.007574,0.527345,0.009690,0.904406,0.000889,128.544387,1.993004
2,Random Forest,0.902025,0.001714,0.612715,0.033143,0.488737,0.017225,0.524814,0.019626,0.900151,0.001761,65.726404,0.919343
3,Decision Tree,0.879892,0.001091,0.487108,0.023389,0.487400,0.018403,0.485856,0.019330,0.879814,0.000989,8.043280,0.046206